import type { ReactElement } from 'react';
import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import LayoutAdmin from '../../components/LayoutAdmin';

import { useState, useEffect } from 'react';

const DashBoard = () => {
  // const [products, setProducts] = useState<any>({});

  useEffect(() => {
    console.log('run useEffect');
  }, []);

  return (
    <div>
      <Head>
        <title>DashBoard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ padding: '20px 0px 50px 0px' }}>Hello</Box>
    </div>
  );
};

DashBoard.getLayout = function getLayout(page: ReactElement) {
  return <LayoutAdmin>{page}</LayoutAdmin>;
};

export default DashBoard;
