import type { ReactElement } from 'react';
import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import type { NextPageWithLayout } from '../_app';
import LayoutShop from '../../components/LayoutShop';

const Shop: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Box display={'flex'}>
          <Box>Shop</Box>
        </Box>
      </Box>
    </div>
  );
};

// const Shop = () => {
Shop.getLayout = function getLayout(page: ReactElement) {
  return <LayoutShop>{page}</LayoutShop>;
};

export default Shop;
