import { ReactElement, useEffect, useState } from 'react';
import {
  Box,
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
  IconButton,
} from '@chakra-ui/react';
import Head from 'next/head';
import type { NextPageWithLayout } from '../_app';
import { IoAdd } from 'react-icons/io5';
import { AiOutlineMinus } from 'react-icons/ai';
import { BsTrash3 } from 'react-icons/bs';
import { CiEdit } from 'react-icons/ci';
import LayoutShop from '../../components/LayoutShop';
import ProductForm from '../../components/ProductForm';
import { getProductsByShop, IProduct } from '../../common/apis/productApi';

const Shop: NextPageWithLayout = () => {
  const [isForm, setIsForm] = useState(false);
  const [products, setProducts] = useState<any[]>([]);

  useEffect(() => {
    async function getProducts() {
      const listProduct = await getProductsByShop();
      setProducts(listProduct);
    }

    getProducts();
  }, []);
  return (
    <div>
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display={'flex'}>
        {/* <Box display={'flex'}>
          <Box>Quản lý sản phẩm</Box>
        </Box> */}
        <TableContainer>
          <Table variant="simple">
            <TableCaption>Thông tin sản phẩm</TableCaption>
            <Thead>
              <Tr>
                <Th>Tên sản phẩm</Th>
                <Th>Ảnh</Th>
                <Th>Giá</Th>
                <Th>Số lượng</Th>
                <Th>Mô tả</Th>
                <Th>Trạng thái</Th>
                <Th>Thao tác</Th>
              </Tr>
            </Thead>
            <Tbody>
              {products.length > 0 &&
                products.map((product) => (
                  <Tr key={product._id}>
                    <Td>
                      <Box
                        sx={{
                          width: '210px',
                          fontSize: '12px',
                          overflow: 'hidden',
                          whiteSpace: 'pre-wrap',
                          display: '-webkit-box',
                          WebkitBoxOrient: 'vertical',
                          WebkitLineClamp: 2,
                        }}
                      >
                        {product.name}
                      </Box>
                    </Td>
                    <Td>
                      <img
                        src={product.avatar}
                        style={{
                          width: '50px',
                          height: '50px',
                          objectFit: 'cover',
                        }}
                      />
                    </Td>
                    <Td isNumeric>{product.price}</Td>
                    <Td>{product.quantity} (cái)</Td>
                    <Td>{product.description}</Td>
                    <Td>{product.status ? 'đang bán' : ''}</Td>
                    <Td>
                      <Box
                        sx={{
                          display: 'flex',
                          justifyContent: 'space-between',
                        }}
                      >
                        <CiEdit size={18} />
                        <BsTrash3 size={16} />
                      </Box>
                    </Td>
                  </Tr>
                ))}
            </Tbody>
            {/* <Tfoot>
              <Tr>
                <Th>To convert</Th>
                <Th>into</Th>
                <Th isNumeric>multiply by</Th>
              </Tr>
            </Tfoot> */}
          </Table>
        </TableContainer>
        <Box>
          <IconButton
            variant="outline"
            colorScheme="teal"
            aria-label="Add"
            icon={isForm ? <AiOutlineMinus /> : <IoAdd />}
            onClick={() => setIsForm(!isForm)}
          />
          {isForm && (
            <Box>
              <ProductForm />
            </Box>
          )}
        </Box>
      </Box>
    </div>
  );
};

// const Shop = () => {
Shop.getLayout = function getLayout(page: ReactElement) {
  return <LayoutShop>{page}</LayoutShop>;
};

export default Shop;
