import { Box, Image, Divider, Button } from '@chakra-ui/react';
import axios from 'axios';
import Head from 'next/head';
import Stars from '../../components/rating/star';
import { BsCartPlus } from 'react-icons/bs';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

// const ProductDetail = () => {
const ProductDetail = (props: any) => {
  const { product } = props;
  // const router = useRouter();
  // const { id } = router.query;

  // const [product, setProduct] = useState<any[]>([]);

  // useEffect(() => {
  //   // async function getProduct(id:string) {
  //   //   const productDetail = await getProductById(id);
  //   //   console.log('productDetail: ', productDetail);

  //   //   setProduct(listProduct);
  //   // }
  //   // console.log(props);

  //   // getProduct(router.query.id);
  //   console.log('pppp: ', typeof router.query.id, id);
  // }, []);
  return (
    <div>
      <Head>
        <title>Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ display: 'flex', width: '1240px', margin: '0px auto' }}>
        <Box sx={{ padding: '16px 0px 16px 16px' }}>
          <Box
            as="img"
            src={product.avatar}
            style={{
              display: 'block',
              maxWidth: '400px',
              width: '400px',
              height: '400px',
              objectFit: 'cover',
            }}
          />
        </Box>
        <Box sx={{ margin: '0px 12px' }}>
          <Divider orientation="vertical" />
        </Box>
        <Box>
          <Box sx={{ padding: '16px 28px 16px 0px' }}>
            <Box
              sx={{
                fontSize: '13px',
                color: 'rgb(36, 36, 36)',
                lineHeight: '20px',
              }}
            >
              Thương hiệu:{' '}
              <span style={{ color: 'rgb(13, 92, 182)' }}>Johnson's Baby</span>
            </Box>
            <Box
              sx={{
                margin: '0px 0px 4px',
                color: 'rgb(36, 36, 36)',
                fontSize: '24px',
                lineHeight: '32px',
              }}
            >
              {product.name}
            </Box>
            <Box sx={{ display: 'flex' }}>
              <Stars star={3} size={'14px'} />{' '}
              <Box
                sx={{
                  cursor: 'pointer',
                  marginLeft: '8px',
                  color: 'rgb(120, 120, 120)',
                  fontSize: '15px',
                }}
              >
                (Xem 802 đánh giá) | Đã bán 5000+
              </Box>
            </Box>
          </Box>
          <Box
            sx={{
              backgroundColor: 'rgb(250, 250, 250)',
              borderRadius: '4px',
              padding: '0px 16px 12px',
              boxSizing: 'border-box',
            }}
          >
            <Box
              sx={{
                fontSize: '32px',
                marginRight: '8px',
                height: '66px',
                fontWeight: 400,
                color: '#FF424E',
              }}
            >
              {product.price} ₫
            </Box>
          </Box>
          <Box
            sx={{
              display: 'flex',
              fontSize: '.875rem',
              alignItems: 'center',
              margin: '20px 0px',
            }}
          >
            <Box
              as="span"
              sx={{
                color: '#757575',
                width: '110px',
              }}
            >
              Loại
            </Box>
            <Box sx={{ fontWeight: 100 }}>
              <Button
                size={'sm'}
                sx={{ marginRight: '8px', fontWeight: 400 }}
                _focus={{
                  color: 'rgb(13, 92, 182)',
                  transform: 'scale(0.98)',
                  borderColor: 'rgb(13, 92, 182)',
                }}
                variant="outline"
              >
                Trắng
              </Button>
              <Button
                size={'sm'}
                sx={{ marginRight: '8px', fontWeight: 400 }}
                _focus={{
                  color: 'rgb(13, 92, 182)',
                  transform: 'scale(0.98)',
                  borderColor: 'rgb(13, 92, 182)',
                }}
                variant="outline"
              >
                Đen
              </Button>
              <Button
                size={'sm'}
                sx={{ marginRight: '8px', fontWeight: 400 }}
                _focus={{
                  color: 'rgb(13, 92, 182)',
                  transform: 'scale(0.98)',
                  borderColor: 'rgb(13, 92, 182)',
                }}
                variant="outline"
              >
                Xanh
              </Button>
            </Box>
          </Box>
          <Box
            sx={{
              display: 'flex',
              color: '#757575',
              fontSize: '.875rem',
              alignItems: 'center',
              margin: '20px 0px',
            }}
          >
            <Box
              as={'span'}
              sx={{
                width: '110px',
              }}
            >
              Số lượng
            </Box>
            <Box sx={{ display: 'flex' }}>
              <Box
                sx={{
                  boxSizing: 'border-box',
                  border: '1px solid rgba(0,0,0,.09)',
                  padding: '1px 6px',
                  width: '32px',
                  height: '32px',
                  textAlign: 'center',
                }}
              >
                -
              </Box>
              <Box
                sx={{
                  display: 'flex',
                  border: '1px solid rgba(0,0,0,.09)',
                  borderLeft: 0,
                  borderRight: 0,
                  width: '50px',
                  height: '32px',
                  justifyContent: 'center',
                  alignItems: 'center',
                }}
              >
                5
              </Box>
              <Box
                sx={{
                  boxSizing: 'border-box',
                  border: '1px solid rgba(0,0,0,.09)',
                  padding: '1px 6px',
                  width: '32px',
                  height: '32px',
                  textAlign: 'center',
                }}
              >
                +
              </Box>
            </Box>
            <Box as="span" sx={{ marginLeft: '15px' }}>
              {product.quantity} sản phẩm có sẵn
            </Box>
          </Box>
          <Box>
            <Button
              leftIcon={<BsCartPlus />}
              variant="outline"
              sx={{ marginRight: '12px', height: '48px' }}
            >
              Thêm vào giỏ hàng
            </Button>
            <Button
              variant="solid"
              sx={{ backgroundColor: '#EE4D2D', color: '#fff', height: '48px' }}
            >
              Mua ngay
            </Button>
          </Box>
        </Box>
      </Box>
    </div>
  );
};

export async function getServerSideProps(context: any) {
  // console.log(context.params);
  const id = context.params.id;
  const { data } = await axios.get(
    `${process.env.NEXT_PUBLIC_APP_API_URL}/product/${id}`,
    { headers: { 'content-type': 'application/json' } }
  );

  return {
    props: {
      product: data,
    }, // will be passed to the page component as props
  };
}

export default ProductDetail;
