// import type { ReactElement } from 'react';
import {
  Box,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  TabIndicator,
  Text,
  Button,
  Image,
} from '@chakra-ui/react';
import Head from 'next/head';
// import type { NextPageWithLayout } from '../_app';
// import LayoutShop from '../../components/LayoutShop';
import TableOrder from '../../components/TableOrder';
import ItemInHistoryOrderCustomer from '../../components/Order/ItemInHistoryOrderCustomer';
import { MdStorefront } from 'react-icons/md';
import {
  getProductsByOrderId,
  getAllProductsOrderOfUser,
} from '../../common/apis/productApi';
import { useState, useEffect } from 'react';

const Order = () => {
  const [products, setProducts] = useState<any>({});

  const handleTabsChange = async () => {
    await getProducts();
  };

  const reloadPage = async () => {
    await getProducts();
  };

  async function getProducts() {
    const listProduct = await getAllProductsOrderOfUser();
    setProducts(listProduct);
  }

  useEffect(() => {
    console.log('run useEffect');
    getProducts();
  }, []);
  console.log('products: ', products);

  return (
    <div>
      <Head>
        <title>My Order</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ padding: '20px 0px 50px 0px' }}>
        <Box display={'flex'} sx={{ width: '70%', margin: '0 auto' }}>
          <Tabs
            position="relative"
            variant="unstyled"
            onChange={handleTabsChange}
          >
            <TabList>
              <Tab sx={{ width: '200px' }}>Tất cả</Tab>
              <Tab sx={{ width: '200px' }}>Chờ xác nhận</Tab>
              <Tab sx={{ width: '200px' }}>Đang giao</Tab>
              <Tab sx={{ width: '200px' }}>Hoàn thành</Tab>
              <Tab sx={{ width: '200px' }}>Đã hủy</Tab>
            </TabList>
            <TabIndicator
              mt="-1.5px"
              height="2px"
              bg="blue.500"
              borderRadius="1px"
            />
            <TabPanels>
              <TabPanel>
                <ItemInHistoryOrderCustomer
                  orders={products.waitForConfirmation}
                  reloadPage={reloadPage}
                />
                <ItemInHistoryOrderCustomer orders={products.delivery} />
                <ItemInHistoryOrderCustomer orders={products.completed} />
                <ItemInHistoryOrderCustomer
                  orders={products.cancelled}
                  reloadPage={reloadPage}
                />
              </TabPanel>
              <TabPanel>
                {products?.waitForConfirmation &&
                products.waitForConfirmation.length !== 0 ? (
                  <ItemInHistoryOrderCustomer
                    orders={products.waitForConfirmation}
                    reloadPage={reloadPage}
                  />
                ) : (
                  <Box
                    sx={{
                      display: 'flex',
                      justifyContent: 'center',
                      alignItems: 'center',
                      minHeight: '300px',
                    }}
                  >
                    <Box>
                      <Image
                        src={'/image_1.png'}
                        sx={{
                          width: '100px',
                          height: '100px',
                          margin: '0 auto',
                        }}
                      />
                      <Box marginTop={'15px'}>Chưa có đơn hàng</Box>
                    </Box>
                  </Box>
                )}
              </TabPanel>
              <TabPanel>
                {products?.delivery && products.delivery.length !== 0 ? (
                  <ItemInHistoryOrderCustomer orders={products.delivery} />
                ) : (
                  <Box
                    sx={{
                      display: 'flex',
                      justifyContent: 'center',
                      alignItems: 'center',
                      minHeight: '300px',
                    }}
                  >
                    <Box>
                      <Image
                        src={'/image_1.png'}
                        sx={{
                          width: '100px',
                          height: '100px',
                          margin: '0 auto',
                        }}
                      />
                      <Box marginTop={'15px'}>Chưa có đơn hàng</Box>
                    </Box>
                  </Box>
                )}
              </TabPanel>
              <TabPanel>
                {products?.completed && products.completed.length !== 0 ? (
                  <ItemInHistoryOrderCustomer orders={products.completed} />
                ) : (
                  <Box
                    sx={{
                      display: 'flex',
                      justifyContent: 'center',
                      alignItems: 'center',
                      minHeight: '300px',
                    }}
                  >
                    <Box>
                      <Image
                        src={'/image_1.png'}
                        sx={{
                          width: '100px',
                          height: '100px',
                          margin: '0 auto',
                        }}
                      />
                      <Box marginTop={'15px'}>Chưa có đơn hàng</Box>
                    </Box>
                  </Box>
                )}
              </TabPanel>
              <TabPanel>
                {products?.cancelled && products.cancelled.length !== 0 ? (
                  <ItemInHistoryOrderCustomer
                    orders={products.cancelled}
                    reloadPage={reloadPage}
                  />
                ) : (
                  <Box
                    sx={{
                      display: 'flex',
                      justifyContent: 'center',
                      alignItems: 'center',
                      minHeight: '300px',
                    }}
                  >
                    <Box>
                      <Image
                        src={'/image_1.png'}
                        sx={{
                          width: '100px',
                          height: '100px',
                          margin: '0 auto',
                        }}
                      />
                      <Box marginTop={'15px'}>Chưa có đơn hàng</Box>
                    </Box>
                  </Box>
                )}
              </TabPanel>
            </TabPanels>
          </Tabs>
        </Box>
      </Box>
    </div>
  );
};

// const Order = () => {
// Order.getLayout = function getLayout(page: ReactElement) {
//   return <LayoutOrder>{page}</LayoutOrder>;
// };

export default Order;
