import type { NextPage } from 'next';
import { useEffect, useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Box } from '@chakra-ui/react';
import Product from './product';
import { getAllProducts } from '../common/apis/productApi';
import { useRouter } from 'next/router';
import Sidebar from '../components/Home/SidebarHome';
import Link from 'next/link';
import { log } from 'console';

const Home: NextPage = () => {
  const router = useRouter();
  const [products, setProducts] = useState<any[]>([]);

  useEffect(() => {
    async function getProducts() {
      const listProduct = await getAllProducts();

      setProducts(listProduct);
    }

    getProducts();
  }, []);

  const handleClickProduct = async (id: string) => {
    await router.push(`/product/${id}`);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ backgroundColor: '#f5f5fa' }}>
        <Box
          sx={{
            display: 'flex',
            width: '96%',
            margin: '0 auto',
            paddingTop: '16px',
          }}
        >
          <Sidebar />
          <Box
            sx={{
              display: 'flex',
              flexWrap: 'wrap',
              // width: '80%',
              height: 'max-content',
            }}
          >
            {products?.map((product) => (
              <Box
                key={product._id}
                sx={{ height: 'max-content' }}
                onClick={() => {
                  handleClickProduct(product._id);
                }}
              >
                <Product
                  name={product.name}
                  image={product.avatar}
                  price={product.price}
                />
              </Box>
            ))}
          </Box>
        </Box>
      </Box>
    </div>
  );
};

export default Home;
